document.writeln("<div class='header'>");
document.writeln("    <div class='header-adorne'>");
document.writeln("    </div>");
document.writeln("    <div class='header-title'>");
document.writeln("        <div class='header-title-logo'>");
document.writeln("            <img src='images/logo.png' alt='logo'>");
document.writeln("        </div>");
document.writeln("        <div class='header-title-text'>");
document.writeln("            <p>中远（北京）实业有限公司</p>");
document.writeln("            <p>COSCO (BEIJING) ENTERPRISES Co., Ltd.</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class='nav'>");
document.writeln("    <div class='nav-adorne'>");
document.writeln("    </div>");
document.writeln("    <div class='nav-button'>");
document.writeln("        <ul class='clear-fix'>");
document.writeln("            <li><a href='#'>首页</a></li>");
document.writeln("            <li><a href='#'>公司简介</a></li>");
document.writeln("            <li><a href='#'>物业管理</a></li>");
document.writeln("            <li><a href='#'>后勤保障</a></li>");
document.writeln("            <li><a href='#'>船员中心</a></li>");
document.writeln("            <li><a href='#'>物流仓储中心</a></li>");
document.writeln("            <li><a href='#'>新闻中心</a></li>");
document.writeln("            <li><a href='#'>企业文化</a></li>");
document.writeln("            <li><a href='#'>招聘信息</a></li>");
document.writeln("            <li><a href='#'>联系我们</a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");